#!/usr/bin/env bash
set -euo pipefail

EDGE_TARGET="${OPENCLAW_DESKTOP_TUNNEL_TARGET:-tesis-edge}"
EDGE_BIND="${OPENCLAW_DESKTOP_TUNNEL_EDGE_BIND:-127.0.0.1:21434}"
if [[ -n "${OPENCLAW_DESKTOP_TUNNEL_LOCAL_BIND:-}" ]]; then
  LOCAL_BIND="${OPENCLAW_DESKTOP_TUNNEL_LOCAL_BIND}"
elif [[ "${OPENCLAW_DESKTOP_RUNTIME:-}" == "llamacpp" ]]; then
  LOCAL_BIND="127.0.0.1:21435"
else
  LOCAL_BIND="127.0.0.1:11434"
fi
COMFY_ENABLED="${OPENCLAW_DESKTOP_TUNNEL_COMFY_ENABLED:-1}"
COMFY_EDGE_BIND="${OPENCLAW_DESKTOP_TUNNEL_COMFY_EDGE_BIND:-127.0.0.1:28000}"
COMFY_LOCAL_BIND="${OPENCLAW_DESKTOP_TUNNEL_COMFY_LOCAL_BIND:-127.0.0.1:8000}"

FORWARDS=(-R "${EDGE_BIND}:${LOCAL_BIND}")
if [[ "${COMFY_ENABLED}" =~ ^(1|true|yes|on)$ ]]; then
  FORWARDS+=(-R "${COMFY_EDGE_BIND}:${COMFY_LOCAL_BIND}")
fi

exec ssh \
  -NT \
  -o ExitOnForwardFailure=yes \
  -o ServerAliveInterval=30 \
  -o ServerAliveCountMax=3 \
  "${FORWARDS[@]}" \
  "${EDGE_TARGET}"
